### PR TITLE
Add support for EPEL-....  adivsories for patch issues

### PR DESCRIPTION
**Pull request by semtexzv**
## Secure Coding Practices Checklist GitHub Link
    - https://github.com/RedHatInsights/secure-coding-checklist

    ## Secure Coding Checklist
    - [ ] Input Validation
    - [ ] Output Encoding
    - [ ] Authentication and Password Management
    - [ ] Session Management
    - [ ] Access Control
    - [ ] Cryptographic Practices
    - [ ] Error Handling and Logging
    - [ ] Data Protection
    - [ ] Communication Security
    - [ ] System Configuration
    - [ ] Database Security
    - [ ] File Management
    - [ ] Memory Management
    - [ ] General Coding Practices

### CODE REVIEW

**Review by aleccohan — CHANGES_REQUESTED** [review]
@semtexzv A couple things with this change, could you please also update the Errata play template to use the same regex?
https://github.com/RedHatInsights/insights-remediations/blob/master/src/templates/static/patchman/errata.yml#L30

Additionally if possible would you be able to add a test or two into the patchman integration tests?  https://github.com/RedHatInsights/insights-remediations/blob/master/src/generator/patchman.integration.js this will help to keep remediations up to date with these new changes:
https://github.com/RedHatInsights/insights-remediations/blob/master/src/generator/patchman.integration.js

Once these changes are made I'll go ahead and re-sign the erratum play template.

**Comment by jiridostal** [comment]
@aleccohan Hey Alec, do you think this can be prioritized to be merged? Or is there anything else needed from our side? Thanks!

**Comment by aleccohan** [comment]
@jiridostal Absolutely!  Taking a look at it now.

**Review by aleccohan — APPROVED** [review]
LGTM!  I've re-signed the playbook and am waiting for the tests to pass before merging

**Pull request merged**
