### PR TITLE
RHINENG-7094 Adjust regex to handle advisory ids correctly

### PR DESCRIPTION
**Pull request by marleystipich2**
## Secure Coding Practices Checklist GitHub Link
    - https://github.com/RedHatInsights/secure-coding-checklist

    ## Secure Coding Checklist
    - [ ] Input Validation
    - [ ] Output Encoding
    - [ ] Authentication and Password Management
    - [ ] Session Management
    - [ ] Access Control
    - [ ] Cryptographic Practices
    - [ ] Error Handling and Logging
    - [ ] Data Protection
    - [ ] Communication Security
    - [ ] System Configuration
    - [ ] Database Security
    - [ ] File Management
    - [ ] Memory Management
    - [ ] General Coding Practices

### CODE REVIEW

**Comment by marleystipich2** [comment]
@rexwhite Hmm the labeler is still failing 🤔 Not sure why because the new signature looks good to me.

**Comment by rexwhite** [comment]
@marleystipich2 It looks like the GitHub labeler has been updated and our config needed updating so I pushed a new config - let's see if that fixes it 😬

The labeler just scans for changes to any static playbook and adds a 're-sign' label to the PR so we don't accidentally deploy stale playbooks.

**Review by rexwhite — APPROVED** [review]
Everything looks good!

**Comment by marleystipich2** [comment]
@rexwhite Sorry, I was on PTO but thanks for fixing the labeler and merging this! 🙂

**Pull request merged**
