### PR TITLE
updated PKG_PATTERN regex

### PR DESCRIPTION
**Pull request by Josca**
it was failing for numbers and capital letters in rpm package name

    ## Secure Coding Practices Checklist GitHub Link
    - https://github.com/RedHatInsights/secure-coding-checklist

    ## Secure Coding Checklist
    - [ ] Input Validation
    - [ ] Output Encoding
    - [ ] Authentication and Password Management
    - [ ] Session Management
    - [ ] Access Control
    - [ ] Cryptographic Practices
    - [ ] Error Handling and Logging
    - [ ] Data Protection
    - [ ] Communication Security
    - [ ] System Configuration
    - [ ] Database Security
    - [ ] File Management
    - [ ] Memory Management
    - [ ] General Coding Practices

### CODE REVIEW

**Comment by Josca** [comment]
@aleccohan @jharting that's quite important bugfix. Please could you check it and merge once you have a minute? Thanks.

**Review by aleccohan — CHANGES_REQUESTED** [review]
@Josca This looks good to me!  Though if you could update the regex in this template to match it, that would be great.  You'll probably have to update a few tests as well with this change:
https://github.com/RedHatInsights/insights-remediations/blob/master/src/templates/static/patchman/packages.yml#L9

**Comment by Josca** [comment]
@aleccohan I see, updated, is it alright now?

**Review by aleccohan — APPROVED** [review]
LGTM merging

**Pull request merged**
