### PR TITLE
Add playbook_runs parameter when listing remediations

### PR DESCRIPTION
**Pull request by mhuth**
Implements https://issues.redhat.com/browse/RHIF-141.

I need to update the unittests too, but it would be nice to get some feedback on what I have done so far.

### CODE REVIEW

**Comment by mhuth** [comment]
For https://issues.redhat.com/browse/RHIF-141.

Adds the playbook_runs structure directly into the remediations list output, but only the first playbook run (if any).  Like so:
```
$ curl -s -X GET -H "$X_RH_IDENTITY" "http://localhost:9002/api/remediations/v1/remediations?limit=4&playbook_runs=true" -H "accept: application/json" | jq .

{
  "data": [
    {
      "id": "9197ba55-0abc-4028-9bbe-269e530f8bd5",
      "name": "Fix Critical CVEs",
      "created_by": {
        "username": "jharting@redhat.com",
        "first_name": "Jozef",
        "last_name": "Hartinger"
      },
      "created_at": "2018-12-05T08:19:36.641Z",
      "updated_by": {
        "username": "jharting@redhat.com",
        "first_name": "Jozef",
        "last_name": "Hartinger"
      },
      "updated_at": "2018-12-05T08:19:36.641Z",
      "issue_count": 0,
      "system_count": 0,
      "resolved_count": 27,
      "needs_reboot": true,
      "archived": true,
      "playbook_runs": {
        "data": [
          {
            "id": "a8799a02-8be9-11e8-9eb6-529269fb1459",
            "executors": [
              {
                "executor_id": "9197ba55-0abc-4028-9bbe-269e530f8bd5",
                "executor_name": "Executor Name",
                "status": "pending",
                "system_count": 0,
                "counts": {
                  "pending": 0,
                  "running": 0,
                  "success": 0,
                  "failure": 0,
                  "canceled": 0
                }
              }
            ],
            "remediation_id": "9197ba55-0abc-4028-9bbe-269e530f8bd5",
            "created_by": {
              "username": "jharting@redhat.com",
              "first_name": "Jozef",
              "last_name": "Hartinger"
            },
            "created_at": "2018-12-05T08:19:36.641Z",
            "updated_at": "2018-12-05T08:19:36.641Z",
            "status": "pending"
          }
        ],
        "meta": {
          "count": 50,
          "total": 114
        }
      }
    }
  ],
  "meta": {
    "count": 50,
    "total": 114
  },
  "links": {
    "value": {
      "first": "/api/remediations/v1/remediations?sort=-updated_at&limit=50&offset=0",
      "last": "/api/remediations/v1/remediations?sort=-updated_at&limit=50&offset=50",
      "next": "/api/remediations/v1/remediations?sort=-updated_at&limit=50&offset=50",
      "previous": null
    }
  }
}
```

**Comment by jiridostal** [comment]
@rexwhite Can you please provide a review on this?

**Comment by rexwhite** [comment]
Hey @jiridostal - I'm aware of this PR I've just been occupied with FedRAMP issues.  I do have comments but need time to collect my thoughts into something actionable, plus this can't be merged into master until the FedRAMP issues are resolved or the two will become entangled.

Just a couple quick notes: this needs tests.  I also don't  like the query parameter.  Both of those are a little tricky (the tests in particular) and I'm more than happy to help with both but I'm a team of one doing 2.5 jobs so I'm afraid I have to beg your patience just a little longer...

**Comment by jiridostal** [comment]
Thank you @rexwhite, appreciate it.

**Comment by rexwhite** [comment]
This all looks good.  I need to coordinate with QE before I merge this, though, since it will automatically get promoted to the commercial stage environment.

**Comment by mhuth** [comment]
Adding some screenshots of how the fields[data]=playbook_runs parameter looks in the Swagger UI.

This screenshot shows the fields[data]=playbook_runs parameter, along will the other query parameters that can be used when doing a GET /remediations ...
Screenshot from 2023-03-28 11-05-42

This screenshot shows the result of executing a query with the 'data[fields]=playbook_runs' parameter present.  Notice the playbook_runs data included in the response ...
Screenshot from 2023-03-28 11-06-35

This screenshot shows passing 'data[fields]=' as a query parameter and notice the playbook_runs data is not included in the response now ...
Screenshot from 2023-03-28 11-13-31

**Review by rexwhite — COMMENTED** [review]
Looks good...

**Pull request merged**
